"""Read-only view over ``demo/`` — the dataset the API serves when there is no
database.

``demo/`` is a frozen, deterministic run of the real pipeline against the
fixture adapter: 30 daily periods x 60 routes x 7 horizons, 75,552 rows, with
the index, the hashes and the publisher's artifacts alongside it. See
``demo/README.md``.

**Everything here is synthetic.** The fares came from a fixture adapter that
makes no network calls. This module exists so the dashboard has a real series
to draw, not so a fixture fare can be passed off as a measurement — every
response built from it carries ``data_source: "demo-synthetic"``, and the
dashboard renders that as a banner.

Loading is lazy and cached: the panel is parsed once on first request and the
per-route aggregates are computed once on top of it. A missing ``demo/``
directory is not an error — :func:`available` returns False and the API says
so, rather than the process failing to boot.
"""

from __future__ import annotations

import json
import logging
from datetime import date, timedelta
from functools import lru_cache
from pathlib import Path
from typing import Any

import pandas as pd

from aerodex.airports import carrier_name, city

logger = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parent.parent
DEMO_DIR = ROOT / "demo"
CONFIG_DIR = ROOT / "config"

DATA_SOURCE = "demo-synthetic"

SYNTHETIC_NOTICE = (
    "Fixture-derived demo data. Every fare in this response was generated by "
    "the fixture adapter, not collected from a live source. Not a measurement."
)


def available() -> bool:
    """True when the demo dataset is present on disk."""
    return (DEMO_DIR / "panel.csv.gz").exists() and (DEMO_DIR / "index.csv").exists()


# ---------------------------------------------------------------------------
# Raw loaders (cached)
# ---------------------------------------------------------------------------


@lru_cache(maxsize=1)
def panel() -> pd.DataFrame:
    """The full demo panel, one row per collected itinerary quote."""
    df = pd.read_csv(DEMO_DIR / "panel.csv.gz")
    df["fare_inr"] = df["fare_inr_paise"] / 100.0
    df["route"] = df["origin"] + "-" + df["destination"]
    return df


@lru_cache(maxsize=1)
def index_series() -> pd.DataFrame:
    """The computed index, one row per daily period."""
    df = pd.read_csv(DEMO_DIR / "index.csv")
    df["period"] = df["period"].astype(str)
    return df


@lru_cache(maxsize=1)
def manifest() -> dict:
    path = DEMO_DIR / "MANIFEST.json"
    return json.loads(path.read_text()) if path.exists() else {}


@lru_cache(maxsize=1)
def artifact(name: str = "index_latest.json") -> dict:
    path = DEMO_DIR / "artifacts" / name
    return json.loads(path.read_text()) if path.exists() else {}


@lru_cache(maxsize=1)
def panel_config() -> dict:
    import yaml

    path = CONFIG_DIR / "panel.yaml"
    if not path.exists():
        return {}
    with path.open() as f:
        return yaml.safe_load(f)


@lru_cache(maxsize=1)
def methodology_config() -> dict:
    import yaml

    path = CONFIG_DIR / "methodology.yaml"
    if not path.exists():
        return {}
    with path.open() as f:
        return yaml.safe_load(f)


@lru_cache(maxsize=1)
def route_weights() -> dict[str, float]:
    """DGCA-derived panel weight per ``ORIGIN-DEST`` key."""
    return {
        f"{r['origin']}-{r['destination']}": float(r.get("weight") or 0.0)
        for r in panel_config().get("routes", [])
    }


# ---------------------------------------------------------------------------
# Derived aggregates (cached)
# ---------------------------------------------------------------------------


@lru_cache(maxsize=1)
def periods() -> list[str]:
    """Every collection period in the panel, ascending."""
    return sorted(panel()["period"].unique().tolist())


@lru_cache(maxsize=1)
def route_daily() -> pd.DataFrame:
    """Per route per period: best fare, median fare and quote count.

    ``best_fare`` is the cheapest all-inclusive economy quote across all seven
    booking horizons — what a traveller would see. ``median_fare`` is the more
    stable number and is what the route cards headline, because the minimum of
    420 quotes jumps around on noise alone.
    """
    df = panel()
    g = df.groupby(["route", "period"], as_index=False).agg(
        best_fare=("fare_inr", "min"),
        median_fare=("fare_inr", "median"),
        mean_fare=("fare_inr", "mean"),
        n_quotes=("fare_inr", "size"),
    )
    return g.sort_values(["route", "period"]).reset_index(drop=True)


@lru_cache(maxsize=1)
def route_cheapest_itinerary() -> dict[str, dict]:
    """The cheapest itinerary per route in the latest period.

    Gives each route card a real carrier, stop count and departure bucket
    instead of a random draw.
    """
    df = panel()
    latest = df[df["period"] == periods()[-1]]
    out: dict[str, dict] = {}
    for route, grp in latest.groupby("route"):
        row = grp.loc[grp["fare_inr"].idxmin()]
        out[str(route)] = {
            "carrier": str(row["carrier"]),
            "cabin": str(row.get("cabin", "economy")).capitalize(),
            "airline": carrier_name(str(row["carrier"])),
            "stops": int(row["stops"]),
            "duration_minutes": int(row["duration_minutes"]),
            "departure_time_bucket": str(row["departure_time_bucket"]),
            "horizon_days": int(row["horizon_days"]),
            "fare_inr": float(row["fare_inr"]),
        }
    return out


def _stops_label(n: int) -> str:
    return "Direct" if n == 0 else f"{n} Stop" if n == 1 else f"{n} Stops"


def _change_class(current: float, previous: float) -> str:
    if previous <= 0:
        return "stable"
    if current < previous * 0.99:
        return "drop"
    if current > previous * 1.01:
        return "rise"
    return "stable"


# ---------------------------------------------------------------------------
# API-shaped builders
# ---------------------------------------------------------------------------


def latest_period() -> str:
    return periods()[-1]


def index_latest() -> dict:
    """Latest index point, preferring the publisher's own artifact."""
    art = artifact()
    idx = index_series()
    last = idx.iloc[-1]
    meth = methodology_config()

    return {
        "index": art.get("index", "AeroDex Airfare Price Index (India)"),
        "period": art.get("period", str(last["period"])),
        "value": float(art.get("value", last["value"])),
        "previous_value": float(idx.iloc[-2]["value"]) if len(idx) > 1 else None,
        "base_period": art.get("base_period", meth.get("base", {}).get("period", "2026-09")),
        "base_value": float(art.get("base_value", 100.0)),
        "coverage_ratio": float(art.get("coverage_ratio", last["coverage_ratio"])),
        "imputed_weight_share": float(
            art.get("imputed_weight_share", last["imputed_weight_share"])
        ),
        "n_quotes": int(art.get("n_quotes", last["n_quotes"])),
        "n_strata_reported": int(last.get("n_strata_reported", 0)),
        "n_routes": len(route_weights()),
        "is_provisional": bool(art.get("is_provisional", True)),
        "config_hash": art.get("config_hash", str(last.get("config_hash", ""))),
        "panel_hash": art.get("panel_hash", str(last.get("panel_hash", ""))),
        "weights_vintage": art.get("weights_vintage", str(last.get("weights_vintage", ""))),
        "output_hash": art.get("output_hash", ""),
        "data_source": DATA_SOURCE,
        "synthetic": True,
        "notice": SYNTHETIC_NOTICE,
    }


def index_history(days: int = 30) -> dict:
    """Headline index series plus per-route fare series over the same periods."""
    idx = index_series().tail(days)
    keep = set(idx["period"])

    headline = [
        {
            "period": str(r["period"]),
            "date": _short_date(str(r["period"])),
            "value": round(float(r["value"]), 4),
            "coverage_ratio": round(float(r["coverage_ratio"]), 5),
            "imputed_weight_share": round(float(r["imputed_weight_share"]), 5),
            "n_quotes": int(r["n_quotes"]),
            "is_base": bool(r["is_base"]),
        }
        for _, r in idx.iterrows()
    ]

    # Per-route fare series, heaviest DGCA weights first — those are the routes
    # that actually move the headline.
    weights = route_weights()
    top = sorted(weights, key=lambda k: weights[k], reverse=True)[:8]

    daily = route_daily()
    daily = daily[daily["period"].isin(keep) & daily["route"].isin(top)]

    routes_meta = []
    for i, key in enumerate(top):
        origin, dest = key.split("-")
        routes_meta.append(
            {
                "key": f"{origin}_{dest}",
                "route": key,
                "label": f"{origin} → {dest}",
                "cities": f"{city(origin)} → {city(dest)}",
                "color": ROUTE_COLORS[i % len(ROUTE_COLORS)],
                "weight": round(weights[key], 6),
            }
        )

    by_period: dict[str, dict[str, Any]] = {}
    for _, r in daily.iterrows():
        period = str(r["period"])
        origin, dest = str(r["route"]).split("-")
        point = by_period.setdefault(
            period, {"period": period, "date": _short_date(period)}
        )
        point[f"{origin}_{dest}"] = round(float(r["median_fare"]), 0)

    data = [by_period[p] for p in sorted(by_period)]

    # Fold the headline index onto the same rows so a chart can switch between
    # "fares in rupees" and "index points" without a second request.
    index_by_period = {h["period"]: h["value"] for h in headline}
    for point in data:
        point["index"] = index_by_period.get(point["period"])

    return {
        "routes": routes_meta,
        "data": data,
        "headline": headline,
        "days": len(headline),
        "data_source": DATA_SOURCE,
        "synthetic": True,
        "notice": SYNTHETIC_NOTICE,
    }


def trackers(limit: int | None = None) -> list[dict]:
    """One card per panel route: fare now, change since the previous period,
    and a sparkline of the route's own recent history."""
    daily = route_daily()
    cheapest = route_cheapest_itinerary()
    weights = route_weights()
    all_periods = periods()
    last = all_periods[-1]
    prev = all_periods[-2] if len(all_periods) > 1 else last

    out: list[dict] = []
    for route, grp in daily.groupby("route"):
        route = str(route)
        grp = grp.sort_values("period")
        cur_row = grp[grp["period"] == last]
        prev_row = grp[grp["period"] == prev]
        if cur_row.empty:
            continue

        price = float(cur_row.iloc[0]["median_fare"])
        best = float(cur_row.iloc[0]["best_fare"])
        prev_price = float(prev_row.iloc[0]["median_fare"]) if not prev_row.empty else price

        change = _change_class(price, prev_price)
        change_amt = abs(price - prev_price)
        change_pct = round(change_amt / prev_price * 100, 1) if prev_price else 0.0

        origin, dest = route.split("-")
        itin = cheapest.get(route, {})
        horizon = int(itin.get("horizon_days", 7))
        dep = date.fromisoformat(last) + timedelta(days=horizon)

        spark = [
            {"v": round(float(v)), "period": str(p)}
            for p, v in zip(grp["period"].tolist(), grp["median_fare"].tolist(), strict=True)
        ][-14:]

        out.append(
            {
                "id": route,
                "from": origin,
                "fromCity": city(origin),
                "to": dest,
                "toCity": city(dest),
                "stops": _stops_label(int(itin.get("stops", 0))),
                "price": round(price),
                "bestPrice": round(best),
                "prevPrice": round(prev_price),
                "change": change,
                "changePct": change_pct,
                "changeAmt": round(change_amt),
                "volume": int(cur_row.iloc[0]["n_quotes"]),
                "airline": itin.get("airline", "—"),
                "carrier": itin.get("carrier", ""),
                "cabin": itin.get("cabin", "Economy"),
                "weight": round(weights.get(route, 0.0), 6),
                "horizonDays": horizon,
                "departureDate": dep.isoformat(),
                "dates": f"{dep.strftime('%b %d')} · {horizon}d out",
                "period": last,
                "updated": f"{last} · morning slot",
                "alertOn": False,
                "data": spark,
            }
        )

    # Heaviest routes first: the panel's own ordering, not an arbitrary one.
    out.sort(key=lambda t: t["weight"], reverse=True)
    return out[:limit] if limit else out


def route_detail(origin: str, destination: str) -> dict | None:
    """Everything the panel holds about one route in the latest period."""
    key = f"{origin}-{destination}"
    df = panel()
    sub = df[df["route"] == key]
    if sub.empty:
        return None

    last = latest_period()
    latest = sub[sub["period"] == last]

    by_horizon = [
        {
            "horizon_days": int(h),
            "departure_date": (date.fromisoformat(last) + timedelta(days=int(h))).isoformat(),
            "best_fare": round(float(g["fare_inr"].min())),
            "median_fare": round(float(g["fare_inr"].median())),
            "n_quotes": int(len(g)),
        }
        for h, g in latest.groupby("horizon_days")
    ]

    by_carrier: list[dict[str, Any]] = [
        {
            "carrier": str(c),
            "airline": carrier_name(str(c)),
            "best_fare": round(float(g["fare_inr"].min())),
            "median_fare": round(float(g["fare_inr"].median())),
            "n_quotes": int(len(g)),
            "share": round(len(g) / len(latest), 4),
        }
        for c, g in latest.groupby("carrier")
    ]
    # Sorted on the number the card headlines, so "cheapest first" is true of
    # what the reader sees rather than of a column that is not on screen.
    by_carrier.sort(key=lambda c: float(c["best_fare"]))

    daily = route_daily()
    series = daily[daily["route"] == key].sort_values("period")

    return {
        "route": key,
        "origin": origin,
        "destination": destination,
        "originCity": city(origin),
        "destinationCity": city(destination),
        "weight": round(route_weights().get(key, 0.0), 6),
        "period": last,
        "byHorizon": sorted(by_horizon, key=lambda h: h["horizon_days"]),
        "byCarrier": by_carrier,
        "series": [
            {
                "period": str(r["period"]),
                "date": _short_date(str(r["period"])),
                "best": round(float(r["best_fare"])),
                "median": round(float(r["median_fare"])),
                "quotes": int(r["n_quotes"]),
            }
            for _, r in series.iterrows()
        ],
        "data_source": DATA_SOURCE,
        "synthetic": True,
        "notice": SYNTHETIC_NOTICE,
    }


def search(origin: str, destination: str, horizon: int, limit: int = 12) -> dict:
    """The actual quotes the panel holds for one route/horizon in the latest
    period — cheapest first. This is what the panel collected, not a booking."""
    key = f"{origin}-{destination}"
    last = latest_period()
    df = panel()
    sub = df[(df["route"] == key) & (df["horizon_days"] == horizon) & (df["period"] == last)]

    quotes = [
        {
            "itineraryKey": str(r["itinerary_key"]),
            "flight": str(r["itinerary_key"]).split("|")[3],
            "carrier": str(r["carrier"]),
            "airline": carrier_name(str(r["carrier"])),
            "fare": round(float(r["fare_inr"])),
            "stops": int(r["stops"]),
            "stopsLabel": _stops_label(int(r["stops"])),
            "durationMinutes": int(r["duration_minutes"]),
            "departureBucket": str(r["departure_time_bucket"]),
        }
        for _, r in sub.sort_values("fare_inr").head(limit).iterrows()
    ]

    dep = date.fromisoformat(last) + timedelta(days=horizon)
    return {
        "route": key,
        "origin": origin,
        "destination": destination,
        "originCity": city(origin),
        "destinationCity": city(destination),
        "horizonDays": horizon,
        "collectedOn": last,
        "departureDate": dep.isoformat(),
        "nQuotes": int(len(sub)),
        "quotes": quotes,
        "data_source": DATA_SOURCE,
        "synthetic": True,
        "notice": SYNTHETIC_NOTICE,
    }


def alerts() -> list[dict]:
    """Threshold crossings derived from the panel.

    There is no per-user alert store yet, so rather than invent an inbox these
    are computed: each route's threshold is the **median of its own daily
    cheapest fare** across the collection window, rounded to ₹100 — "what a
    good fare on this route normally looks like". A route whose cheapest quote
    today sits below that line is *triggered*, i.e. today is cheaper than usual
    for that corridor; the rest are *watching*.

    Deterministic, and every number traces back to rows in
    ``demo/panel.csv.gz``.
    """
    daily = route_daily()
    all_periods = periods()
    last = all_periods[-1]
    cheapest = route_cheapest_itinerary()
    weights = route_weights()

    out: list[dict[str, Any]] = []
    for route, grp in daily.groupby("route"):
        route = str(route)
        cur_rows = grp[grp["period"] == last]
        if grp.empty or cur_rows.empty:
            continue

        threshold = round(float(grp["best_fare"].median()) / 100) * 100
        current = round(float(cur_rows.iloc[0]["best_fare"]))
        median_today = round(float(cur_rows.iloc[0]["median_fare"]))
        origin, dest = route.split("-")

        out.append(
            {
                "id": route,
                "route": f"{origin} → {dest}",
                "origin": origin,
                "destination": dest,
                "originCity": city(origin),
                "destinationCity": city(dest),
                "airline": cheapest.get(route, {}).get("airline", "Any"),
                "threshold": threshold,
                "current": current,
                "medianToday": median_today,
                "low": round(float(grp["best_fare"].min())),
                "high": round(float(grp["best_fare"].max())),
                "delta": current - threshold,
                "deltaPct": round((current - threshold) / threshold * 100, 1) if threshold else 0.0,
                "triggered": current < threshold,
                "weight": round(weights.get(route, 0.0), 6),
                "period": last,
                "basis": f"median cheapest fare, {all_periods[0]} … {last}",
            }
        )

    out.sort(key=lambda a: (not a["triggered"], float(a["delta"])))
    return out


def routes() -> list[dict]:
    """The panel definition, enriched for the route picker and the map."""
    from aerodex.airports import airport_dict

    weights = route_weights()
    daily = route_daily()
    last = latest_period()
    latest = daily[daily["period"] == last].set_index("route")

    out: list[dict[str, Any]] = []
    for key, weight in weights.items():
        origin, dest = key.split("-")
        row = latest.loc[key] if key in latest.index else None
        out.append(
            {
                "id": key,
                "origin": airport_dict(origin),
                "destination": airport_dict(dest),
                "weight": round(weight, 6),
                "medianFare": round(float(row["median_fare"])) if row is not None else None,
                "bestFare": round(float(row["best_fare"])) if row is not None else None,
                "quotes": int(row["n_quotes"]) if row is not None else 0,
            }
        )
    out.sort(key=lambda r: float(r["weight"]), reverse=True)
    return out


def collection_nodes() -> list[dict]:
    """Panel coverage by region of the country.

    A route is attributed to the region of *both* its endpoints — the panel is
    hub-and-spoke (six origin hubs, 23 airports), so counting origins alone
    would report "North India: DEL" and hide the 22 spokes it reaches. Counts
    are real row counts from the latest period; the regional split is the
    ``region`` field in :mod:`aerodex.airports`.
    """
    from aerodex.airports import AIRPORTS

    df = panel()
    last = latest_period()
    latest = df[df["period"] == last]

    def region_of(code: str) -> str:
        a = AIRPORTS.get(code)
        return a.region if a else "Unknown"

    buckets: dict[str, dict] = {}
    for (origin, dest), grp in latest.groupby(["origin", "destination"]):
        route = f"{origin}-{dest}"
        for code in (str(origin), str(dest)):
            b = buckets.setdefault(
                region_of(code), {"quotes": 0, "airports": set(), "routes": set()}
            )
            b["quotes"] += len(grp)
            b["airports"].add(code)
            b["routes"].add(route)

    order = ["North", "South", "West", "East"]
    ordered = [r for r in order if r in buckets] + sorted(set(buckets) - set(order))

    out = []
    for region in ordered:
        b = buckets[region]
        codes = sorted(b["airports"])
        out.append(
            {
                "id": region,
                "region": f"{region} India",
                "airports": codes,
                "detail": ", ".join(codes),
                "status": "active" if b["quotes"] else "idle",
                "routes": len(b["routes"]),
                "queries": b["quotes"],
            }
        )
    return out


def pipeline_status() -> dict:
    """Provenance and compliance facts for the dashboard's integrity panel.

    Everything here is read from ``demo/MANIFEST.json``, ``config/panel.yaml``
    and ``config/methodology.yaml`` — nothing is asserted by the dashboard.
    """
    man = manifest()
    meth = methodology_config()
    pcfg = panel_config()
    art = artifact()
    idx = index_series()

    collection = pcfg.get("collection", {})
    min_gap = collection.get("min_seconds_between_requests_per_host", 20)
    slots = [s["id"] for s in pcfg.get("slots", [])]

    return {
        "run": {
            "source": man.get("source", "fixture"),
            "synthetic": bool(man.get("synthetic", True)),
            "warning": man.get("warning", SYNTHETIC_NOTICE),
            "generatedBy": man.get("generated_by", ""),
            "start": man.get("start"),
            "end": latest_period(),
            "days": man.get("days", len(idx)),
            "slot": man.get("slot", "morning"),
        },
        "panel": {
            "routes": man.get("routes", len(route_weights())),
            "horizons": man.get("horizons", pcfg.get("horizons_days", [])),
            "strata": man.get("strata", 0),
            "rows": man.get("panel", {}).get("rows", int(len(panel()))),
            "slots": slots,
            "coverageHole": man.get("panel", {}).get("coverage_hole"),
        },
        "quotes": man.get("quotes", {}),
        "hashes": {
            "config": art.get("config_hash", ""),
            "panel": art.get("panel_hash", ""),
            "output": art.get("output_hash", ""),
            "calendar": man.get("calendar_config_hash", ""),
            "panelConfig": man.get("panel_config_hash", ""),
        },
        "methodology": {
            "elementary": meth.get("elementary", {}).get("formula", "jevons"),
            "aggregation": meth.get("aggregation", {}).get("formula", "lowe"),
            "weightsVintage": meth.get("aggregation", {}).get("weights_vintage", ""),
            "imputationCeiling": meth.get("imputation", {}).get("max_weight_share", 0.05),
            "basePeriod": meth.get("base", {}).get("period", ""),
            "revisionPolicy": meth.get("revision", {}).get("policy", ""),
        },
        "quality": {
            "minCoverageRatio": float(idx["coverage_ratio"].min()),
            "maxImputedWeightShare": float(idx["imputed_weight_share"].max()),
            "ceilingBreached": bool(
                idx["imputation_ceiling_breached"].astype(str).eq("True").any()
            ),
        },
        "compliance": {
            "minSecondsBetweenRequests": min_gap,
            "rules": [
                "robots.txt parsed and honoured at run time; unreachable means disallowed",
                "No authentication, CAPTCHA solving, fingerprint spoofing or proxies",
                f"Minimum {min_gap}s between requests to the same host",
                "Blocked sources are dropped and the coverage ratio is published",
            ],
        },
        "verify": {
            "command": (
                "aerodex verify --panel-csv demo/panel.csv.gz "
                "--hashes demo/expected_hashes.json"
            ),
            "description": (
                "Recomputes the index from the archived panel and diffs the output hash. "
                "The published number is reproducible from the published inputs."
            ),
        },
        "refusalDemo": man.get("breach", {}),
        "data_source": DATA_SOURCE,
    }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

ROUTE_COLORS = [
    "#2456E8", "#F04438", "#12B76A", "#F59E0B", "#8B5CF6",
    "#EC4899", "#06B6D4", "#84CC16", "#F97316", "#6366F1",
]


def _short_date(period: str) -> str:
    try:
        return date.fromisoformat(period).strftime("%b %d")
    except ValueError:
        return period
